# change the followings to match your Github username and repo name
baseurl: "/gangwang" # the name of your github repo
url: "https://steeelheart.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Gang's Personal Site"
description: Personal site template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Gang Wang
author-bio: Associate Professor@UDelaware. Researcher on digital platforms, social & peer influence; Love reading; start to play drum;  # change to false to hide
author-image: Gang2015edited.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Research
  permalink: research
- text: Teaching
  permalink: teaching
- text: Blog
  permalink: blog

# use false to turn off any social media links
google-scholar:: https://scholar.google.com/citations?user=lywEk9IAAAAJ&hl=en
twitter: https://twitter.com/steeelheart
facebook: false
instagram: false
github: false
linkedin: https://linkedin.com/
medium: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
